{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "778c8402-72d0-49d0-97d7-54afd599dc54",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-07 01:09:50,531\tINFO worker.py:1634 -- Connecting to existing Ray cluster at address: 127.0.0.1:6379...\n",
      "2024-12-07 01:09:50,582\tINFO worker.py:1819 -- Connected to Ray cluster.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fault Tolerance Test: 4 Workers with 1 Failures (over 3 trials)\n",
      "Simulated failure for task: ObjectRef(3b86534cae58b4adffffffffffffffffffffffff0200000001000000)\n",
      "\u001b[33m(raylet)\u001b[0m A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: a50339a56b26a0fbce2376c7c0dc3a24ed20cd7c02000000 Worker ID: 8969c3f864a32de23aceaadeb313403d7db92bfe4ad4916b0917c81d Node ID: ddf46cc29f954199e1fdd9d4ca119f09663a730b83b3f48dcd7b7dc7 Worker IP address: 127.0.0.1 Worker port: 10014 Worker PID: 90932 Worker exit type: SYSTEM_ERROR Worker exit detail: The leased worker has unrecoverable failure. Worker is requested to be destroyed when it is returned. RPC Error message: Connection reset; RPC Error details: \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m A module that was compiled using NumPy 1.x cannot be run in\n",
      "\u001b[36m(pid=90988)\u001b[0m NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "\u001b[36m(pid=90988)\u001b[0m versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "\u001b[36m(pid=90988)\u001b[0m Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m If you are a user of the module, the easiest solution will be to\n",
      "\u001b[36m(pid=90988)\u001b[0m downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "\u001b[36m(pid=90988)\u001b[0m We expect that some modules will need time to support NumPy 2.\n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m Traceback (most recent call last):  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\workers\\default_worker.py\", line 289, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     worker.main_loop()\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\worker.py\", line 920, in main_loop\n",
      "\u001b[36m(pid=90988)\u001b[0m     self.core_worker.run_task_loop()\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 361, in get_execution_info\n",
      "\u001b[36m(pid=90988)\u001b[0m     self._wait_for_function(function_descriptor, job_id)\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 428, in _wait_for_function\n",
      "\u001b[36m(pid=90988)\u001b[0m     if self.fetch_and_register_remote_function(key) is True:\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "\u001b[36m(pid=90988)\u001b[0m     function = pickle.loads(serialized_function)\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\__init__.py\", line 84, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from .base import clone\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\base.py\", line 19, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\__init__.py\", line 11, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from ._chunking import gen_batches, gen_even_slices\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_chunking.py\", line 8, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from ._param_validation import Interval, validate_params\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 14, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from .validation import _is_arraylike_not_scalar\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 26, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_array_api.py\", line 11, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from .fixes import parse_version\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py\", line 24, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     import pandas as pd\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py\", line 26, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from pandas.compat import (\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\compat\\__init__.py\", line 27, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from pandas.compat.pyarrow import (\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\compat\\pyarrow.py\", line 8, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     import pyarrow as pa\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pyarrow\\__init__.py\", line 65, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     import pyarrow.lib as _lib\n",
      "\u001b[36m(pid=90988)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\numpy\\core\\_multiarray_umath.py\", line 44, in __getattr__\n",
      "\u001b[36m(pid=90988)\u001b[0m     raise ImportError(msg)\n",
      "\u001b[36m(pid=90988)\u001b[0m ImportError: \n",
      "\u001b[36m(pid=90988)\u001b[0m A module that was compiled using NumPy 1.x cannot be run in\n",
      "\u001b[36m(pid=90988)\u001b[0m NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "\u001b[36m(pid=90988)\u001b[0m versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "\u001b[36m(pid=90988)\u001b[0m Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m If you are a user of the module, the easiest solution will be to\n",
      "\u001b[36m(pid=90988)\u001b[0m downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "\u001b[36m(pid=90988)\u001b[0m We expect that some modules will need time to support NumPy 2.\n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m A module that was compiled using NumPy 1.x cannot be run in\n",
      "\u001b[36m(pid=90988)\u001b[0m NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "\u001b[36m(pid=90988)\u001b[0m versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "\u001b[36m(pid=90988)\u001b[0m Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m If you are a user of the module, the easiest solution will be to\n",
      "\u001b[36m(pid=90988)\u001b[0m downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "\u001b[36m(pid=90988)\u001b[0m We expect that some modules will need time to support NumPy 2.\n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m Traceback (most recent call last):  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\workers\\default_worker.py\", line 289, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     worker.main_loop()\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\worker.py\", line 920, in main_loop\n",
      "\u001b[36m(pid=90988)\u001b[0m     self.core_worker.run_task_loop()\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 361, in get_execution_info\n",
      "\u001b[36m(pid=90988)\u001b[0m     self._wait_for_function(function_descriptor, job_id)\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 428, in _wait_for_function\n",
      "\u001b[36m(pid=90988)\u001b[0m     if self.fetch_and_register_remote_function(key) is True:\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\n",
      "\u001b[36m(pid=90988)\u001b[0m     function = pickle.loads(serialized_function)\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\__init__.py\", line 84, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from .base import clone\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\base.py\", line 19, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\__init__.py\", line 11, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from ._chunking import gen_batches, gen_even_slices\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_chunking.py\", line 8, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from ._param_validation import Interval, validate_params\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py\", line 14, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from .validation import _is_arraylike_not_scalar\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\validation.py\", line 26, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\_array_api.py\", line 11, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from .fixes import parse_version\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\sklearn\\utils\\fixes.py\", line 24, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     import pandas as pd\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py\", line 49, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from pandas.core.api import (\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\core\\api.py\", line 1, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     from pandas._libs import (\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\_libs\\__init__.py\", line 17, in <module>\n",
      "\u001b[36m(pid=90988)\u001b[0m     import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]\n",
      "\u001b[36m(pid=90988)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[36m(pid=90988)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\numpy\\core\\_multiarray_umath.py\", line 44, in __getattr__\n",
      "\u001b[36m(pid=90988)\u001b[0m     raise ImportError(msg)\n",
      "\u001b[36m(pid=90988)\u001b[0m ImportError: \n",
      "\u001b[36m(pid=90988)\u001b[0m A module that was compiled using NumPy 1.x cannot be run in\n",
      "\u001b[36m(pid=90988)\u001b[0m NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\n",
      "\u001b[36m(pid=90988)\u001b[0m versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "\u001b[36m(pid=90988)\u001b[0m Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m If you are a user of the module, the easiest solution will be to\n",
      "\u001b[36m(pid=90988)\u001b[0m downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "\u001b[36m(pid=90988)\u001b[0m We expect that some modules will need time to support NumPy 2.\n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90988)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "\u001b[36m(pid=90928)\u001b[0m \n",
      "2024-12-07 01:09:55,831\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Trial 1: Average R^2 Score after failures: 0.6190, Average Training Time: 0.01 seconds\n",
      "Simulated failure for task: ObjectRef(8f663780d3989ddbffffffffffffffffffffffff0200000001000000)\n",
      "Trial 2: Average R^2 Score after failures: 0.6129, Average Training Time: 0.01 seconds\n",
      "Simulated failure for task: ObjectRef(be6acd8b66376146ffffffffffffffffffffffff0200000001000000)\n",
      "Trial 3: Average R^2 Score after failures: 0.6265, Average Training Time: 0.01 seconds\n",
      "Overall Average R^2 Score after failures: 0.6195\n",
      "\n",
      "Fault Tolerance Test: 8 Workers with 2 Failures (over 3 trials)\n",
      "Simulated failure for task: ObjectRef(c453a022e4a6723cffffffffffffffffffffffff0200000001000000)\n",
      "Simulated failure for task: ObjectRef(ba8a006fe2c26cd1ffffffffffffffffffffffff0200000001000000)\n",
      "Trial 1: Average R^2 Score after failures: 0.6317, Average Training Time: 0.01 seconds\n",
      "Simulated failure for task: ObjectRef(3f2f06a8fa342b1bffffffffffffffffffffffff0200000001000000)\n",
      "Simulated failure for task: ObjectRef(e1dfc33e08f0b074ffffffffffffffffffffffff0200000001000000)\n",
      "Trial 2: Average R^2 Score after failures: 0.6317, Average Training Time: 0.01 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-12-07 01:09:56,688\tERROR worker.py:422 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Simulated failure for task: ObjectRef(cdc13c092b12eb09ffffffffffffffffffffffff0200000001000000)\n",
      "Simulated failure for task: ObjectRef(fb88e879dfe75486ffffffffffffffffffffffff0200000001000000)\n",
      "Trial 3: Average R^2 Score after failures: 0.6314, Average Training Time: 0.01 seconds\n",
      "Overall Average R^2 Score after failures: 0.6316\n",
      "\n",
      "Communication Overhead for 4 workers: 0.14 seconds\n",
      "Communication Overhead for 8 workers: 0.25 seconds\n",
      "\n",
      "Resource Usage:\n",
      "Total CPU Cores: 12\n",
      "Available CPU Cores: 11.0\n",
      "Total Memory: 7.73 GB\n",
      "Used Memory: 6.80 GB\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(pid=90928)\u001b[0m A module that was compiled using NumPy 1.x cannot be run in\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m NumPy 2.1.3 as it may crash. To support both 1.x and 2.x\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m versions of NumPy, modules must be compiled with NumPy 2.0.\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m If you are a user of the module, the easiest solution will be to\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m downgrade to 'numpy<2' or try to upgrade the affected module.\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m We expect that some modules will need time to support NumPy 2.\u001b[32m [repeated 4x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m Traceback (most recent call last):  File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\workers\\default_worker.py\", line 289, in <module>\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     worker.main_loop()\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\worker.py\", line 920, in main_loop\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     self.core_worker.run_task_loop()\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 361, in get_execution_info\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     self._wait_for_function(function_descriptor, job_id)\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 428, in _wait_for_function\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     if self.fetch_and_register_remote_function(key) is True:\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 290, in fetch_and_register_remote_function\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     function = pickle.loads(serialized_function)\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\pandas\\_libs\\__init__.py\", line 17, in <module>\u001b[32m [repeated 23x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     from .base import clone\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     from .utils._estimator_html_repr import _HTMLDocumentationLinkMixin, estimator_html_repr\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     from ._chunking import gen_batches, gen_even_slices\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     from ._param_validation import Interval, validate_params\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     from .validation import _is_arraylike_not_scalar\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     from ..utils._array_api import _asarray_with_order, _is_numpy_namespace, get_namespace\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     from .fixes import parse_version\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     import pandas as pd\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     from pandas.compat import (\n",
      "\u001b[36m(pid=90928)\u001b[0m     from pandas.compat.pyarrow import (\n",
      "\u001b[36m(pid=90928)\u001b[0m     import pyarrow as pa\n",
      "\u001b[36m(pid=90928)\u001b[0m     import pyarrow.lib as _lib\n",
      "\u001b[36m(pid=90928)\u001b[0m Traceback (most recent call last):\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m   File \"C:\\Users\\PMLS\\anaconda3\\Lib\\site-packages\\numpy\\core\\_multiarray_umath.py\", line 44, in __getattr__\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     raise ImportError(msg)\u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m ImportError: \u001b[32m [repeated 2x across cluster]\u001b[0m\n",
      "\u001b[36m(pid=90928)\u001b[0m     from pandas.core.api import (\n",
      "\u001b[36m(pid=90928)\u001b[0m     from pandas._libs import (\n",
      "\u001b[36m(pid=90928)\u001b[0m     import pandas._libs.pandas_datetime  # noqa: F401 # isort: skip # type: ignore[reportUnusedImport]\n"
     ]
    }
   ],
   "source": [
    "import ray\n",
    "import numpy as np\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.datasets import fetch_california_housing\n",
    "from sklearn.model_selection import train_test_split\n",
    "import time\n",
    "import psutil\n",
    "\n",
    "# Initialize Ray\n",
    "ray.init(ignore_reinit_error=True, dashboard_port=8265)\n",
    "\n",
    "# Load California Housing Dataset and increase the size\n",
    "def load_data():\n",
    "    data = fetch_california_housing()\n",
    "    X, y = data.data, data.target\n",
    "    \n",
    "    # Increase the size of the dataset by tripling the data\n",
    "    X = np.tile(X, (6, 1))  # Repeat the data three times (for X)\n",
    "    y = np.tile(y, 6)       # Repeat the target values three times (for y)\n",
    "    \n",
    "    return train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "\n",
    "# Linear regression training function\n",
    "@ray.remote\n",
    "def train_worker(X, y):\n",
    "    start_time = time.time()  # Start timer for the worker\n",
    "    model = LinearRegression()\n",
    "    model.fit(X, y)\n",
    "    score = model.score(X, y)  # R^2 score\n",
    "    training_time = time.time() - start_time  # Calculate training time for this worker\n",
    "    return score, training_time\n",
    "\n",
    "# Fault Tolerance Test with Average Calculation\n",
    "def measure_fault_tolerance(num_workers, num_failures, X_train, y_train, num_trials=5):\n",
    "    print(f\"\\nFault Tolerance Test: {num_workers} Workers with {num_failures} Failures (over {num_trials} trials)\")\n",
    "\n",
    "    trial_results = []\n",
    "\n",
    "    for trial in range(num_trials):\n",
    "        workers = []\n",
    "        split_X = np.array_split(X_train, num_workers)\n",
    "        split_y = np.array_split(y_train, num_workers)\n",
    "\n",
    "        # Launch workers\n",
    "        for i in range(num_workers):\n",
    "            workers.append(train_worker.remote(split_X[i], split_y[i]))\n",
    "\n",
    "        # Simulate failures\n",
    "        for _ in range(num_failures):\n",
    "            if workers:\n",
    "                failed_worker = workers.pop(np.random.randint(len(workers)))\n",
    "                ray.cancel(failed_worker, force=True)\n",
    "                print(f\"Simulated failure for task: {failed_worker}\")\n",
    "\n",
    "        # Collect results from surviving workers\n",
    "        results = []\n",
    "        training_times = []\n",
    "        for worker in workers:\n",
    "            try:\n",
    "                result, worker_training_time = ray.get(worker)\n",
    "                results.append(result)\n",
    "                training_times.append(worker_training_time)\n",
    "            except Exception as e:\n",
    "                print(f\"Task {worker} failed with error: {e}\")\n",
    "\n",
    "        if results:\n",
    "            avg_score = np.mean(results)\n",
    "            avg_training_time = np.mean(training_times)\n",
    "            trial_results.append(avg_score)\n",
    "            print(f\"Trial {trial + 1}: Average R^2 Score after failures: {avg_score:.4f}, Average Training Time: {avg_training_time:.2f} seconds\")\n",
    "        else:\n",
    "            print(f\"Trial {trial + 1}: No surviving workers completed their tasks.\")\n",
    "            trial_results.append(0)\n",
    "\n",
    "    # Calculate overall average fault tolerance score\n",
    "    overall_avg_score = np.mean(trial_results)\n",
    "    print(f\"Overall Average R^2 Score after failures: {overall_avg_score:.4f}\\n\")\n",
    "    return overall_avg_score\n",
    "\n",
    "# Resource monitoring function\n",
    "def monitor_resource_usage():\n",
    "    total_cores = psutil.cpu_count(logical=True)\n",
    "    available_cores = ray.available_resources().get(\"CPU\", 0)\n",
    "    total_memory = psutil.virtual_memory().total / (1024 ** 3)  # GB\n",
    "    used_memory = (total_memory - psutil.virtual_memory().available / (1024 ** 3))\n",
    "\n",
    "    print(f\"Total CPU Cores: {total_cores}\")\n",
    "    print(f\"Available CPU Cores: {available_cores}\")\n",
    "    print(f\"Total Memory: {total_memory:.2f} GB\")\n",
    "    print(f\"Used Memory: {used_memory:.2f} GB\")\n",
    "\n",
    "# Measure communication overhead\n",
    "def measure_communication_overhead(num_workers, X_train, y_train):\n",
    "    start_time = time.time()\n",
    "\n",
    "    split_X = np.array_split(X_train, num_workers)\n",
    "    split_y = np.array_split(y_train, num_workers)\n",
    "\n",
    "    # Launch workers and collect results\n",
    "    workers = [train_worker.remote(split_X[i], split_y[i]) for i in range(num_workers)]\n",
    "    ray.get(workers)\n",
    "\n",
    "    end_time = time.time()\n",
    "    communication_time = end_time - start_time\n",
    "    print(f\"Communication Overhead for {num_workers} workers: {communication_time:.2f} seconds\")\n",
    "\n",
    "# Main execution\n",
    "if __name__ == \"__main__\":\n",
    "    X_train, X_test, y_train, y_test = load_data()\n",
    "\n",
    "    # Test fault tolerance with different configurations (2, 4, 8, and 10 workers)\n",
    "    for num_workers in [2, 4, 8, 10]:\n",
    "        measure_fault_tolerance(num_workers=num_workers, num_failures=2, X_train=X_train, y_train=y_train, num_trials=3)\n",
    "\n",
    "        # Measure communication overhead\n",
    "        measure_communication_overhead(num_workers=num_workers, X_train=X_train, y_train=y_train)\n",
    "\n",
    "    # Monitor resource usage\n",
    "    print(\"\\nResource Usage:\")\n",
    "    monitor_resource_usage()\n",
    "\n",
    "    ray.shutdown()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "233bb4e8-e315-4ae0-97aa-2486d3cacceb",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
